apiVersion: v1
kind: Pod
metadata:
  name: easy-ge-pod
spec:
  containers:
  - name: easy-ge-container
    image: elsayed91/easy_ge:python3.10
    volumeMounts:
    - name: config-volume
      mountPath: /data
  volumes:
  - name: config-volume
    hostPath:
      # Replace with the actual path to the config file on the host machine
      path: /path/to/your_config_file.yaml 
      type: File
