Source:
  Name: MyTaxiDataIM # An assigned name for the data source that will be used
  Processor: Pandas # Can be "SparkDF" or "Pandas"
  Properties: 
    InMemory:
      DataFrameName: df # Only for "FileSystem"
    # File:
    #   FilePath: "./sample_data.csv" # Only for "FileSystem"

Backend:
  ExpectationSuiteName: yellow_expectations
  Filesystem:
    WorkDir: "/home/lestrang/wrapexp"


Report:
  NamingRegex: "%Y%m%d%H%M-yellow" # Report naming style

Outputs:
  GenerateDocs: True # Whether to generate data docs
  StoreResults: True # Whether to store validation results
  ResultsDict:
    Save: True # Whether to save the results object
    Format: COMPLETE  # Can be "BOOLEAN_ONLY", "BASIC", "SUMMARY", or "COMPLETE"
