Source:
  Name: MyData
  Processor: Pandas
  Properties: 
    InMemory:
      DataFrameName: "my_df"

Backend:
  ExpectationSuiteName: default
  GCS:
    Project: "my_project"
    Bucket: "my_bucket"
    Prefix: great_expectations

Report:
  NamingRegex: "%Y%m%d%H%M-mydata"

Outputs:
  GenerateDocs: True
  SaveSummaryTableAsCSV: True
