name: CI/CD Pipeline

name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install poetry and dependencies
      run: |
        pip install poetry
        poetry install --dev --all-extras
    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Check import order with isort
      run: |
        poetry run isort --check-only --diff .
    - run: poetry run pytest tests/ -s

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/easy_ge:latest

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install poetry and dependencies
      run: |
        pip install poetry
        poetry install
    - name: Bump version
      run: |
        poetry version patch
    - name: Build and publish
      run: |
        poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}

